services:
  app:
    image: lscr.io/linuxserver/blender:4.0.2-ls99
    volumes:
      - ../..:/workspaces:cached
    environment:
      # specify the same value as your local environement
      - PUID=1000 # id -u
      - PGID=1000 # id -g
      - TZ=Etc/UTC # cat /etc/timezone
