on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: lscr.io/linuxserver/blender:4.0.2-ls99
    steps:
      - uses: actions/checkout@v4

      # setup
      - run: blender --background --python .devcontainer/setup.py
      - run: sh .devcontainer/setup.sh

      # test
      - run: blender --background --python-exit-code 1 --python tests/e2e.py

  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          path: src/
